zth/rescript-relay

- .gitignore
- example/package.json
- packages/reason-relay/build.sh
- syncDev.sh
Ran `./syncDev.sh` and ran into a couple of issues
> Fix syncDev.sh

- reason-relay-documentation/docs/getting-started.md
this is a little typo I found in the parameter name
> nit: fix parameter

- reason-relay-documentation/docs/subscriptions.md
- Add documentation for subscriptions.
Closes: #37
> document subscriptions

- reason-relay-documentation/docs/using-with-hasura.md
This PR adds a guide to setting up Hasura with Reason-Relay. Related to issue: #84 .
Let me know of any changes you think are required 👍
> Add guide to integrating reason-relay with Hasura

- packages/reason-relay/language-plugin/webpack.config.js
- packages/reason-relay/package.json
- packages/reason-relay/yarn.lock
Fixes https://github.com/zth/reason-relay/issues/78.
> fix bs-platform version issue with language-plugin

- .github/workflows/bindings.yml
- .github/workflows/build-release.yml
- .github/workflows/integration-tests.yml
- .github/workflows/language-plugin.yml
- example/yarn.lock
- packages/reason-relay/__tests__/Test_localPayload-tests.js
- packages/reason-relay/compiler/compiler-cli.js
I tweaked a few things to make CI more reliable (use frozen-lockfile, check if (generated) files are modified compared to what's committed, etc.
Right now, the CI just exits with 1 when files are modified but I could also throw with an explanation if you prefer.
I'm actually thinking about creating a dedicated github action for this ^^
> CI cleanup

- packages/reason-relay/src/ReasonRelay.res
- packages/reason-relay/src/ReasonRelay.resi
Added missing bindings for environment.retain method.
> Added missing bindings for environment.retain method.

- reason-relay-documentation/docs/migrating-from-javascript-typescript-incrementally.md
- reason-relay-documentation/sidebars.js
I will continue to improve it as I go along with my own migration process.
> Added doc about migrating from JS/TS incrementally

- packages/reason-relay-bin/lib/PrintState.re
- packages/reason-relay-bin/lib/Printer.re
- packages/reason-relay-bin/test/Tests.re
- packages/reason-relay/__tests__/Test_mutation-tests.js
- packages/reason-relay/__tests__/Test_mutation.res
- packages/reason-relay/__tests__/__generated__/TestMutationInline_user_graphql.res
- packages/reason-relay/__tests__/__generated__/TestMutationWithInlineFragmentSetOnlineStatusMutation_graphql.res
- packages/reason-relay/__tests__/__generated__/TestMutationWithOnlyFragmentSetOnlineStatusMutation_graphql.res
> Mutation types fragmentrefs fix

- CHANGELOG.md
- packages/rescript-relay/src/RescriptRelay.res
- packages/rescript-relay/src/RescriptRelay.resi
- rescript-relay-documentation/docs/api-reference.md
- rescript-relay-documentation/docs/interacting-with-the-store.md
- rescript-relay-documentation/docs/relay-environment.md
- rescript-relay-documentation/sidebars.js
Closes https://github.com/zth/rescript-relay/issues/46
> Missing field handlers

- rescript-relay-documentation/docs/experimental-router.md
Here's a few suggestions to the excellent docs on the experimental router
> Beginners perspective on router docs

- rescript-relay-documentation/docs/experimental-router.md
As per our talk yesterday just updated to match all the type in prepare
> Match all types in prepare

- rescript-relay-documentation/docs/making-queries.md
> Update Broken Link to useLazyLoadQuery

- packages/rescript-relay/src/experimental-router/RescriptRelayRouter.res
- rescript-relay-documentation/docs/experimental-router.md
Attempt to remove the dependency on `url-parse` (which was causing problems for me using vite)
> Removing dependency on url-parse

- CHANGELOG.md
- packages/rescript-relay/__tests__/Test_query.res
- packages/rescript-relay/bsconfig.json
- packages/rescript-relay/bsconfig.release.json
- packages/rescript-relay/package.json
- packages/rescript-relay/rescript-relay-ppx/library/Query.re
- packages/rescript-relay/src/RescriptRelay.res
- packages/rescript-relay/src/RescriptRelay.resi
- packages/rescript-relay/yarn.lock
- rescript-relay-documentation/docs/getting-started.md
- rescript-relay-documentation/docs/making-queries.md
Closes https://github.com/zth/rescript-relay/issues/209
> Remove reason promise

- packages/rescript-relay/src/experimental-router/RescriptRelayRouter.res
Hi @zth we needed a tabIndex so here's a PR suggesting to add that to the experimental router.
> Add tabindex

- rescript-relay-documentation/docs/rescript-relay-cli.md
Simple example of how to keep fields safe from removal. Thanks for the help 👍🏻
> Document how to keep fields safe from removal

- packages/rescript-relay/__tests__/TestRelayUserResolver.res
- packages/rescript-relay/__tests__/Test_relayResolvers-tests.js
- packages/rescript-relay/__tests__/Test_relayResolvers.res
- packages/rescript-relay/__tests__/__generated__/TestRelayResolversQuery_graphql.res
- packages/rescript-relay/__tests__/__generated__/TestRelayResolvers_user_graphql.res
- packages/rescript-relay/__tests__/__generated__/TestRelayUserResolver_graphql.res
- packages/rescript-relay/package.json
- packages/rescript-relay/relay.config.js
- packages/rescript-relay/rescript-relay-ppx/library/RelayResolverFragment.re
- packages/rescript-relay/rescript-relay-ppx/library/RescriptRelayPpxLibrary.re
- packages/rescript-relay/yarn.lock
Closes https://github.com/zth/rescript-relay/compare/relay-resolvers.
> Support Relay Resolvers

- CHANGELOG.md
- packages/rescript-relay/__tests__/Test_nodeInterface-tests.js
- packages/rescript-relay/__tests__/Test_nodeInterface.res
- packages/rescript-relay/__tests__/__generated__/TestNodeInterfaceOnAbstractTypeQuery_graphql.res
- packages/rescript-relay/__tests__/__generated__/TestNodeInterface_user_graphql.res
- packages/rescript-relay/src/utils.js
Closes https://github.com/zth/rescript-relay/issues/324
> fix issue with top level node field, and add tests

- rescript-relay-documentation/docs/interfaces.md
- rescript-relay-documentation/sidebars.js
Hi!
I added some minimal documentation about `interfaces`.
> Docs: Add a section about interfaces

- packages/rescript-relay-cli/__tests__/formatUtils.test.ts
- packages/rescript-relay-cli/formatUtils.ts
Closes #343 
Hey @zth 👋 
Your proposed solution worked pretty well, but I wanted to do a little bit more. Instead of only ignoring commented operations, I tried to format them as well.
> CLI - Handle commented operations

- packages/rescript-relay/src/RescriptRelay.res
- packages/rescript-relay/src/RescriptRelay.resi
> Add Environment isServer option

- packages/rescript-relay/package.json
It's already a peer dependency.
> Remove rescript from dependencies

- CHANGELOG.md
- LOCAL_DEVELOPMENT.md
- packages/rescript-relay/src/RescriptRelay.res
- packages/rescript-relay/src/RescriptRelay.resi
@zth I wanted to add some tests as well but I wasn't able to compile the newly added queries/fragments. If you could provide with some instructions that would be great.
> Fix linked record related cache updaters

- CHANGELOG.md
- packages/rescript-relay/__tests__/ProvidedVariables.res
- packages/rescript-relay/__tests__/Test_providedVariables-tests.js
- packages/rescript-relay/__tests__/Test_providedVariables.res
- packages/rescript-relay/__tests__/__generated__/RelaySchemaAssets_graphql.res
- packages/rescript-relay/__tests__/__generated__/TestProvidedVariablesQuery_graphql.res
- packages/rescript-relay/__tests__/__generated__/TestProvidedVariables_user_graphql.res
- packages/rescript-relay/__tests__/schema.graphql
- packages/rescript-relay/src/RescriptRelay_Internal.res
- rescript-relay-documentation/docs/using-fragments.md
https://relay.dev/docs/api-reference/graphql-and-directives/#provided-variables
Fixes https://github.com/zth/rescript-relay/issues/294
> Implement provided variables

- CHANGELOG.md
> LSP improvements

- CHANGELOG.md
- packages/rescript-relay/__tests__/__generated__/TestRelayResolversQuery_graphql.res
- packages/rescript-relay/package.json
- packages/rescript-relay/src/RescriptRelay.res
- packages/rescript-relay/src/RescriptRelay.resi
- packages/rescript-relay/yarn.lock
- rescript-relay-documentation/docs/getting-started.md
Closes https://github.com/zth/rescript-relay/issues/429
> upgrade to Relay 15

- CHANGELOG.md
- packages/rescript-relay/bsconfig.json
- packages/rescript-relay/package.json
- packages/rescript-relay/src/ReactDOMExperimental.res
- packages/rescript-relay/src/RescriptRelay.res
- packages/rescript-relay/yarn.lock
- rescript-relay-documentation/docs/getting-started.md
Closes https://github.com/zth/rescript-relay/issues/421.
> upgrade to jsx v4

- CHANGELOG.md
- build-ci.sh
- packages/rescript-relay/scripts/release-postinstall.js
Closes https://github.com/zth/rescript-relay/issues/380
> ship prebuilt m1 version of the ppx

- CHANGELOG.md
- packages/rescript-relay/__tests__/Test_customScalars-tests.js
- packages/rescript-relay/__tests__/Test_customScalars.res
- packages/rescript-relay/__tests__/TestsUtils.res
- packages/rescript-relay/__tests__/__generated__/TestCustomScalarsQuery_graphql.res
- packages/rescript-relay/__tests__/schema.graphql
- packages/rescript-relay/__tests__/utils-tests.js
- packages/rescript-relay/relay.config.js
- packages/rescript-relay/src/utils.js
- Fixes converted custom scalars accidentally being traversed
- Fixes custom scalars that are arrays being accidentally traversed
Closes https://github.com/zth/rescript-relay/issues/407
> Fix custom scalar issues

- example/bsconfig.json
- example/package.json
- example/yarn.lock
A member of the discord had trouble getting the example to build. These are the changes that fixed it for him
> Bump example to rescript-relay v2.2.0

- CHANGELOG.md
- packages/rescript-relay/__tests__/Test_requiredFieldLogger-tests.js
- packages/rescript-relay/__tests__/Test_requiredFieldLogger.res
- packages/rescript-relay/src/RescriptRelay.res
- packages/rescript-relay/src/RescriptRelay.resi
Solves https://github.com/zth/rescript-relay/issues/478
> Use untagged variants for Logger + relay_resolver.error support

- CHANGELOG.md
- packages/rescript-relay/__tests__/Test_catch-tests.js
- packages/rescript-relay/__tests__/Test_catch.res
- packages/rescript-relay/__tests__/TestsUtils.res
- packages/rescript-relay/__tests__/__generated__/TestCatchLoggedInUserPropQuery_graphql.res
- packages/rescript-relay/__tests__/__generated__/TestCatchMemberPropNestedQuery_graphql.res
- packages/rescript-relay/__tests__/__generated__/TestCatchMemberPropQuery_graphql.res
- packages/rescript-relay/__tests__/__generated__/TestCatchMembersPropQuery_graphql.res
- packages/rescript-relay/__tests__/__generated__/TestCatchUser_user_graphql.res
- packages/rescript-relay/src/RescriptRelay.res
- packages/rescript-relay/src/RescriptRelay.resi
Closes https://github.com/zth/rescript-relay/issues/544
> Implement catch result type

- CHANGELOG.md
- packages/rescript-relay/__tests__/Test_prefetchablePagination-tests.js
- packages/rescript-relay/__tests__/Test_prefetchablePagination.res
- packages/rescript-relay/__tests__/__generated__/TestPrefetchablePaginationQuery_graphql.res
- packages/rescript-relay/__tests__/__generated__/TestPrefetchablePaginationRefetchQuery_graphql.res
- packages/rescript-relay/__tests__/__generated__/TestPrefetchablePagination_user__edges_graphql.res
- packages/rescript-relay/__tests__/__generated__/TestPrefetchablePagination_user_graphql.res
- packages/rescript-relay/rescript-relay-ppx/library/Fragment.ml
- packages/rescript-relay/rescript-relay-ppx/library/RescriptRelayPpxLibrary.ml
- packages/rescript-relay/rescript-relay-ppx/library/Util.ml
- packages/rescript-relay/src/RescriptRelay_Fragment.res
- packages/rescript-relay/src/RescriptRelay_Fragment.resi
Closes https://github.com/zth/rescript-relay/issues/546
> usePrefetchableForwardPagination
