zth/rescript-relay

example/README.md
When running the example for the first time, it wasn't super clear to me which port the app was running on without digging through the webpack config. This PR shows new users info in the README for when they first run the project.
If you know a quick way to show this clearly in console output, I think that would be better but I couldn't find an answer with a quick google so this appears an intermediate solution to me.
=> Update README to include port information

packages/reason-relay/__tests__/Test_subscription.re, packages/reason-relay/src/ReasonRelay.re, packages/reason-relay/src/ReasonRelay.rei
Update bindings for `subscriptionFunction`
[Relay type](https://github.com/facebook/relay/blob/master/packages/relay-runtime/network/RelayNetworkTypes.js#L102)
```typescript
/**
* A function that executes a GraphQL subscription operation, returning zero or
* more raw server responses over time.
*/
export type SubscribeFunction = (
request: RequestParameters,
variables: Variables,
cacheConfig: CacheConfig,
) => RelayObservable<GraphQLResponse>;
```
=> Update subscriptionFunction bindings

packages/reason-relay/__tests__/Test_mutation.re, packages/reason-relay/src/ReasonRelay.re, packages/reason-relay/src/ReasonRelay.rei
cc @renanmav 
Thanks for giving this a shot! I think what might've been confusing is that there was quite a few places where the `Js.Nullable` unwrapping needed to be removed. Plus the signature of `commitMutationPromised` needed to be changed too, which I didn't tell you 🙁Sorry!
Anyway, I think you got hit by a weird type inference thing (it telling you that `optimisticResponse` needed changing), which was probably caused by the fact that I didn't tell you to change the signature of `commitMutationPromised`.
Do these changes make sense to?
=> fix: commitMutation's response type isn't actually nullable in Relay

CHANGELOG.md, packages/reason-relay/__tests__/TestProviders.re, packages/reason-relay/__tests__/Test_pagination.re, packages/reason-relay/__tests__/Test_refetching.re, packages/reason-relay/package.json, packages/reason-relay/src/ReactExperimental.re, packages/reason-relay/src/ReactExperimental.rei, packages/reason-relay/yarn.lock
- Update `bs-platform` and  `reason-react`
- Remove bindings that are now in `reason-react`
- Remove helper function `renderConcurrentRootAtElementWithId`
- Getting closer to not have to depend on specific react version.
- Use official community bindings for  `Suspense`
=> Update reason react

CHANGELOG.md, packages/reason-relay/src/ReactExperimental.rei, packages/reason-relay/src/ReasonRelay.re, packages/reason-relay/src/ReasonRelay.rei
I added external and BS annotations to interface files and removed unnecessary additional functions to have cleaner and leaner bindings.
I also removed the trailing underscores from internal functions to ensure their use is tracked by the compiler and made use of BS new JS parsing.
That divided by 2 the number of lines of the JS output in ReasonRelay.bs.js, which should benefit to runtime performance.
Good luck for reviewing this ^^
=> clean bindings and their interface files

packages/reason-relay/__tests__/Test_paginationInNode.re, packages/reason-relay/__tests__/Test_paginationUnion.re, packages/reason-relay/__tests__/__generated__/TestPaginationInNode_query_graphql.re, packages/reason-relay/__tests__/__generated__/TestPaginationUnion_query_graphql.re, packages/reason-relay/language-plugin/src/generator/UtilsPrinter.re, packages/reason-relay/language-plugin/src/transformer/TypesTransformer.re
Relay only allows one `@connection` per operation/fragment - no need to generate a unique name for `getConnetionNodes`.
=> Rename generated getConnectionNodes function

CHANGELOG.md, packages/reason-relay/__tests__/Test_localPayload-tests.js, packages/reason-relay/__tests__/Test_localPayload.re, packages/reason-relay/__tests__/__generated__/TestCustomScalarsQuery_graphql.re, packages/reason-relay/__tests__/__generated__/TestFragmentQuery_graphql.re, packages/reason-relay/__tests__/__generated__/TestLocalPayloadQuery_graphql.re, packages/reason-relay/__tests__/__generated__/TestLocalPayload_user_graphql.re, packages/reason-relay/__tests__/__generated__/TestMissingFieldHandlersMeQuery_graphql.re, packages/reason-relay/__tests__/__generated__/TestMissingFieldHandlersQuery_graphql.re, packages/reason-relay/__tests__/__generated__/TestMutationQuery_graphql.re, packages/reason-relay/__tests__/__generated__/TestNodeInterfaceQuery_graphql.re, packages/reason-relay/__tests__/__generated__/TestPaginationInNodeQuery_graphql.re, packages/reason-relay/__tests__/__generated__/TestPaginationInNodeRefetchQuery_graphql.re, packages/reason-relay/__tests__/__generated__/TestPaginationInNode_query_graphql.re, packages/reason-relay/__tests__/__generated__/TestPaginationUnionQuery_graphql.re, packages/reason-relay/__tests__/__generated__/TestPaginationUnionRefetchQuery_graphql.re, packages/reason-relay/__tests__/__generated__/TestQuery_graphql.re, packages/reason-relay/__tests__/__generated__/TestRefetchingInNodeQuery_graphql.re, packages/reason-relay/__tests__/__generated__/TestRefetchingInNodeRefetchQuery_graphql.re, packages/reason-relay/__tests__/__generated__/TestRefetchingInNode_user_graphql.re, packages/reason-relay/__tests__/__generated__/TestRefetchingQuery_graphql.re, packages/reason-relay/__tests__/__generated__/TestRefetchingRefetchQuery_graphql.re, packages/reason-relay/__tests__/__generated__/TestRefetching_user_graphql.re, packages/reason-relay/__tests__/__generated__/TestUnionFragmentQuery_graphql.re, packages/reason-relay/__tests__/__generated__/TestUnionsQuery_graphql.re, packages/reason-relay/language-plugin/src/transformer/PrintState.re, packages/reason-relay/reason-relay-ppx/library/ReasonRelayPpxLibrary.re, packages/reason-relay/reason-relay-ppx/library/Util.re, packages/reason-relay/src/ReasonRelay.re, packages/reason-relay/src/ReasonRelay.rei
This generates a `commitLocalPayload` for any query annotated with `@raw_response_type`, which lets you easily commit local only data in a type safe way as if it were an actual server response. This can be used for a bunch of things, most notably local state management via Relay.
The API looks roughly like this:
```
module Query = [%relay.query {|
query SomeQuery {
loggedInUser {
lastActiveAt
}
}
|}];
...
Query.commitLocalPayload(~environment, ~variables=(), ~payload={ loggedInUser: { lastActive: someTimestamp } });
```
Check out the added test in this diff for another example/more info.
=> Generate commitLocalPayload for elgible queries

packages/reason-relay/compiler/compiler-cli.js
The reason-relay-compiler currently only exits with an error code when it 
detects an issue with its own configuration. In all other cases it exits with 
the status code 0.
This is problematic in cases where the error code is used in build pipelines. 
For example when a reason build should only be started if the relay compiler has 
completed successfully.
This commit propagates the error code from the child process of the 
relay-compiler to be the exit code of the reason-relay-compiler. This ensures 
that bash scripts such as `yarn reason-relay-compiler && bsb -make-world` work 
as a user may expect (only compile Reason when the Relay artifacts could be 
compiled).
=> Propagate the error code for the relay-compiler

packages/reason-relay-bin/bin/ReasonRelayBin.re, packages/reason-relay-bin/copyIntoPlace.sh, packages/reason-relay-bin/lib/PrintState.re, packages/reason-relay-bin/lib/Types.re, packages/reason-relay/language-plugin/src/ReasonRelayBin.ts, packages/reason-relay/language-plugin/src/RelayReasonGenerator.ts, packages/reason-relay/language-plugin/src/__tests__/languagePlugin-tests.ts, packages/reason-relay/language-plugin/src/transformer/transformerUtils.ts
This is an attempt to tighten up the API some for working with the new store updater directives in Relay (`@appendEdge`, `@appendNode` and friends).
The store updater directives all work by accepting a list of connection IDs to add/remove edges/nodes from after a mutation or subscription has run. 
The part of this that trips people up usually is that it's the `dataId` of the connection Relay wants, not the connection key or anything else you as a user set up yourself. You get the `dataId` of a connection by asking for the `__id` field on the connection itself, which is Relay's `dataId`. It looks like this:
```
...some fragment...
myConnectionField(first: $count, after: $cursor) @connection(key: "SomeKey_goes_here") {
__id # This will return the `dataId` for this connection
}
```
Now, with …
=> Type list of connection IDs as dataId

packages/reason-relay-bin/bin/ReasonRelayBin.re, packages/reason-relay-bin/lib/ParseFlowTypes.re, packages/reason-relay-bin/lib/PrintState.re, packages/reason-relay-bin/lib/Printer.re, packages/reason-relay-bin/lib/Types.re, packages/reason-relay-bin/lib/Utils.re, packages/reason-relay/language-plugin/src/__tests__/__snapshots__/languagePlugin-tests.ts.snap
This adds support for comments on the generated types, and adding a comment to any connection record hinting that it's possible to use the generated `getConnectionNodes` helper to turn the connection into a non-nullable list of nodes.
=> Support comments on generated types

build-ci.sh
Bundle prebuilt *.bs.js files into the release package to allow compiled code delivery use cases
=> Allow compiled code delivery use cases

packages/reason-relay-bin/bin/dune, packages/reason-relay/reason-relay-ppx/bin/dune
I think this should fix the glibc errors, and the executables don't seem to get too big.
=> Attempt to statically link executables

CHANGELOG.md, packages/rescript-relay/__tests__/__generated__/TestPaginationInNode_query_graphql.res, packages/rescript-relay/__tests__/__generated__/TestPaginationUnion_query_graphql.res, packages/rescript-relay/__tests__/__generated__/TestRefetchingInNode_user_graphql.res, packages/rescript-relay/__tests__/__generated__/TestRefetching_user_graphql.res, packages/rescript-relay/language-plugin/src/formatGeneratedModule.ts, packages/rescript-relay/language-plugin/src/utils/__tests__/processConcreteText-tests.ts, packages/rescript-relay/language-plugin/src/utils/processConcreteText.ts
relay compiler generates require calls which break
es6 builds. By offloading importing to bsb we can
support both es6 and commonjs transparently and easily
=> Offload importing nodes in refetch queries to bsb

packages/rescript-relay/__tests__/Test_mutation.resi, packages/rescript-relay/__tests__/Test_subscription.resi, packages/rescript-relay/bsconfig.json, packages/rescript-relay/rescript-relay-ppx/library/FragmentUtils.re, packages/rescript-relay/rescript-relay-ppx/library/Mutation.re, packages/rescript-relay/rescript-relay-ppx/library/Query.re, packages/rescript-relay/rescript-relay-ppx/library/Subscription.re
This would happen when writing an interface file for a module using RescriptRelay.
For testing I enabled warnings as errors and added interface files for `Test_mutation.res` and `Test_subscription.res` that would fail with warning 60 before.
I checked and you don't actually need to reenable the disabled warnings afterwards, they would still be raised in the file where the PPX is used.
=> remove warnings for unused values, types, modules

packages/rescript-relay-cli/index.ts
Use child process spawn over exec to avoid running the buffer dry.
This should fix the problem with unused fields not being picked up.
=> Run reanalyze with spawn

packages/rescript-relay-cli/fileUtils.ts
This PR lifts the requirement that the relay config must be defined in `relay.config.js`. Relay will try to load it from `relay.config.js` or `package.json`. So there shouldn't be a need for a hard requirement of having it in `relay.config.js`
=> Make it possible to have the relay config in package.json

packages/rescript-relay/__tests__/Test_requiredFieldLogger-tests.js, packages/rescript-relay/__tests__/Test_requiredFieldLogger.res, packages/rescript-relay/__tests__/__generated__/TestRequiredFieldLoggerQuery_graphql.res, packages/rescript-relay/src/RescriptRelay.res, packages/rescript-relay/src/RescriptRelay.resi
👋  Let me know whether this binding looks good to you. I wanted to make it very close to the original JS one, except that the function accepts labeled arguments instead of a single argument which is an object.
The `kind` type might be awkward to interact with since it's a polymorphic variants with dots, so perhaps you'd rather have something more idiomatic even though it would diverge from the JS type. 
I added a test that pretty much covers the basic functionality, but let me know whether we should also test it with the `THROW` action.
=> Support setting a requiredFieldLogger

rescript-relay-documentation/docs/making-queries.md
fixed typo (`usePreloaed` -> `usePreloaded`)
=> Docs: fix typo

packages/rescript-relay/package.json, packages/rescript-relay/rescript-relay-ppx/library/FragmentUtils.re, packages/rescript-relay/rescript-relay-ppx/library/Mutation.re, packages/rescript-relay/rescript-relay-ppx/library/Query.re, packages/rescript-relay/src/RescriptRelay.res, packages/rescript-relay/src/RescriptRelay.resi
All hook imports are available from `react-relay/index.js` (specified in
`main` in the `package.json`) as of react-relay 11.0.0.
Bundlers have no issues in resolving `react-relay/hooks` to
`react-relay/hooks.js` but NodeJs `require` or `import` calls are more
strict, which means that `import * as Hooks from "react-relay/hooks"`
fails in a NodeJs environment.
By importing from the package's primary entry point we ensure that
Node's file resolver is also happy.
The peer dependency is bumped to require at least react-relay 11.0.0
which introduced the change. `=>` is used because it keeps the
open-ended upper bound that `*` also had.
The react-relay commit that makes the changes (and the tags it's in) 
can be found here: https://github.com/facebook/relay/commit/2d253c073fab38072c6e1db0c723484b …
=> Import hooks from main `react-relay` file

packages/rescript-relay/rescript-relay-ppx/bin/RescriptRelayPpxApp.re, packages/rescript-relay/rescript-relay-ppx/bin/dune, packages/rescript-relay/rescript-relay-ppx/library/Util.re, packages/rescript-relay/rescript-relay-ppx/library/dune, packages/rescript-relay/rescript-relay-ppx/package.json, packages/rescript-relay/rescript-relay-ppx/test/dune, packages/rescript-relay/rescript-relay-ppx/testExe/RunRescriptRelayPpxTests.re, packages/rescript-relay/rescript-relay-ppx/testExe/dune
I couldn't actually get esy to run after removing these dependencies so the lockfiles might need to be updated
This should allow rescript-relay to work with melange.
=> Remove ocaml-migrate-parsetree

packages/rescript-relay/package.json
Closes #355
Can't be tested until it's on npm but should be good I think. That is something I am using in various places in rescript-react-native packages.
=> Fix incorrect `react-relay` peerDependencies version

packages/rescript-relay/src/RescriptRelay.res
When running Jest on a file that uses `%relay` the `React.Context` is undefined when trying to call `React.Context.provider(context)`. Moving it to only run when using `<Provider />` solves the problem.
jest.config.js
```js
/*
* For a detailed explanation regarding each configuration property, visit:
* https://jestjs.io/docs/en/configuration.html
*/
module.exports = {
// An array of file extensions your modules use
collectCoverage: true,
moduleFileExtensions: [
"js",
"mjs",
],
// The glob patterns Jest uses to detect test files
testMatch: [
"**/__tests__/**/*_test.mjs",
],
// A map from regular expressions to paths to transformers
"transform": {
"^.+\\.m?js$": "babel-jest"
},
// An array of regexp pattern strings that are matched against all source file paths, matched files will skip …
```
=> Fix issue running Jest, where React.Context is undefined

packages/rescript-relay/src/RescriptRelay.res, packages/rescript-relay/src/RescriptRelay.resi
https://github.com/facebook/relay/blob/b6c6b7d28a0121f97ad20d17c716c3b905ee6c82/packages/relay-runtime/store/RelayModernStore.js#L429
Found it's usage here https://github.com/vercel/next.js/pull/33892/files#diff-785b30f413e5f6cb7213e3c49e073fd5758dca3315febd2f12630f35fca7ecf3R49
=> Add undocumented holdGC  method on relay store

CHANGELOG.md, packages/rescript-relay/__tests__/Test_localPayload-tests.js, packages/rescript-relay/__tests__/Test_mutation-tests.js, packages/rescript-relay/__tests__/Test_mutation.res, packages/rescript-relay/__tests__/__generated__/RelaySchemaAssets_graphql.res, packages/rescript-relay/__tests__/__generated__/TestMutationSetOnlineStatusComplexMutation_graphql.res, packages/rescript-relay/__tests__/schema.graphql, packages/rescript-relay/__tests__/utils-tests.js, packages/rescript-relay/relay.config.js, packages/rescript-relay/src/utils.js
if the json is not mangled with, the test should pass.
This should be the desired for any scalar I think
=> stop mangling with JSON scalars as a field of a mutation input

CHANGELOG.md, packages/rescript-relay/package.json, packages/rescript-relay/yarn.lock
=> Use ReScript 10

CHANGELOG.md, packages/rescript-relay-cli/commands/removeUnusedFieldsCommand.ts
I've started working on updating the `node` version in CI from `14` to `16`.
But the lint script started failing because of `rescript-relay-cli remove-unused-fields --ci --verbose` exiting with code `1`. 
Here's the error with `debug` on:
After looking at the source code, several hours of different tries, and multiple wild guesses, I've found the solution. It worked fine before because the `npx` with `node@14` doesn't have the prompt.
For some reason, I couldn't reproduce the error locally and only in CI, but I've tested the fix using https://pnpm.io/cli/patch, and it solved the problem.
=> Fix remove-unused-fields in CI

CHANGELOG.md, packages/rescript-relay/__tests__/Test_nullableVariables-tests.js, packages/rescript-relay/__tests__/Test_nullableVariables.res, packages/rescript-relay/__tests__/__generated__/RelaySchemaAssets_graphql.res, packages/rescript-relay/__tests__/__generated__/TestNullableVariablesMutation_graphql.res, packages/rescript-relay/__tests__/__generated__/TestNullableVariablesQuery_graphql.res
Closes https://github.com/zth/rescript-relay/issues/348
This introduces a directive `@rescriptRelayNullableVariables` on operations that will allow you to leverage `Js.Nullable.t` to send `null` explicitly to your APIs.
You can test this in your project by running `yarn add rescript-relay@support-nullable-variables`.
How it works in a nutshell:
```rescript
module Mutation = %relay(`
mutation TestNullableVariablesMutation($avatarUrl: String) @rescriptRelayNullableVariables {
updateUserAvatar(avatarUrl: $avatarUrl) {
user {
avatarUrl
}
}
}
`)
// All optional variables in this operation can now be `null`, which will be preserved and sent to your server.
Mutation.commitMutation(~environment=RelayEnvironment.environment, ~variables={avatarUrl: Js.Nullable.null}, ())
// Or if you want to send a …
```
=> Support null variables

CHANGELOG.md, packages/rescript-relay/__tests__/RelayRouter.res, packages/rescript-relay/__tests__/RelayRouter__Types.res, packages/rescript-relay/__tests__/TestDeferredComponent.res, packages/rescript-relay/__tests__/Test_deferredComponent.res, packages/rescript-relay/rescript-relay-ppx/.ocamlformat, packages/rescript-relay/rescript-relay-ppx/library/DeferredComp.re, packages/rescript-relay/rescript-relay-ppx/library/RescriptRelayPpxLibrary.re, packages/rescript-relay/rescript-relay-ppx/library/Transform.ml
Works around JSXv4 issues for deferred components. You now need to annotate any component you want to use with `%relay.deferredComponent` with `@relay.deferredComponent`.
=> Jsxv4 deferred ppx

CHANGELOG.md, packages/rescript-relay/scripts/release-postinstall.js
Without this fix, I frequently get the following error:
```
node:fs:3003
binding.copyFile(
^
Error: ENOENT: no such file or directory, copyfile '/Users/paul/code/miriad/packages/web/node_modules/rescript-relay/ppx-macos-latest' -> '/Users/paul/code/miriad/packages/web/node_modules/rescript-relay/ppx'
at Object.copyFileSync (node:fs:3003:11)
at copyPlatformBinaries (/Users/paul/code/miriad/packages/web/node_modules/rescript-relay/postinstall.js:102:6)
at Object.<anonymous> (/Users/paul/code/miriad/packages/web/node_modules/rescript-relay/postinstall.js:177:7)
at Module._compile (node:internal/modules/cjs/loader:1376:14)
at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
at Module.load (node:internal/modules/cjs/loader:1207:32)
at Module._load …
```
=> avoid ENOENT error when rebuilding deps

packages/rescript-relay/scripts/release-postinstall.js
I fixed the issue in copyPlatformBinaries earlier but I forgot to do it for removeInitialBinaries, now the postinstall script should be idempotent.
=> Patch postinstall.js number 2

packages/rescript-relay/rescript-relay-ppx/library/Fragment.ml
[The CI seems unhappy with compiling the rust project](https://github.com/ValdemarGr/rescript-relay/actions/runs/8929383024/job/24527042667)
=> hide use and useOpt when @inline is given to a fragment

rescript-relay-documentation/docs/api-reference.md, rescript-relay-documentation/docs/enums.md, rescript-relay-documentation/docs/getting-started.md, rescript-relay-documentation/docs/making-queries.md, rescript-relay-documentation/docs/migrating-to-v3.md, rescript-relay-documentation/docs/mutations.md, rescript-relay-documentation/docs/pagination.md, rescript-relay-documentation/docs/refetching-and-loading-more-data.md, rescript-relay-documentation/docs/subscriptions.md, rescript-relay-documentation/docs/the-node-interface.md, rescript-relay-documentation/docs/tutorial/10-mutations-updates.md, rescript-relay-documentation/docs/tutorial/3-query-basics.md, rescript-relay-documentation/docs/tutorial/4-fragments.md, rescript-relay-documentation/docs/tutorial/5-arrays-and-lists.md, rescript-relay-documentation/docs/tutorial/6-queries-for-interaction.md, rescript-relay-documentation/docs/tutorial/8-refetchable-fragments.md, rescript-relay-documentation/docs/tutorial/9-connections-pagination.md, rescript-relay-documentation/docs/unions.md, rescript-relay-documentation/docs/using-fragments.md, rescript-relay-documentation/docs/variables.md
Ready to merge when `v3` release is published (not rc).
Here is what changed:
- updated getting started with new required package versions
- include how to setup rescript.json on Windows in getting started
- remove trailing units
- stop using Belt module in examples and assume RescriptCore is globally open
- use non-deprecated React hooks in examples (`useCallback5` -> `useCallback`)
- stop using `makeVariables` in examples and remove it from docs
=> Update docs reflecting v3 changes

rescript-relay-documentation/blog/2024-08-06-rescript-relay-3.0.0-released.md
Small drive-by fix I noticed in the examples while reading the release notes.
Looks like a great release—the community is very lucky to have you!
=> [Docs] Fix inconsistency in names in input union example in 3.0 release notes

rescript-relay-documentation/docs/introduction.md, rescript-relay-documentation/docusaurus.config.js
Hey @zth! 
Was clicking around the rescript-relay website and found what i think might be an old link in the footer.
- Fixed "broken" link footer to point to docs introduction
- Removed introduction page that was marked as "WIP" (but I don't think it's intended to be done?)
=> Minor docs page fix
